# Generated by Django 4.2 on 2023-04-04 20:55

from django.db import migrations, models
import your_space_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('your_space_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default=your_space_app.models.default_profile_image, upload_to='profile_images'),
        ),
    ]
