# Generated by Django 4.2 on 2023-04-08 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('your_space_app', '0003_alter_comment_post_alter_comment_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='post',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
