# Generated by Django 4.2 on 2023-04-10 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('your_space_app', '0005_post_category_post_subject_post_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default='No bio yet'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, default='Nowhere', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(default='User', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='./img/image.png', upload_to='profile_images'),
        ),
    ]
